version: '3.8'

services:
  # Vechnost Telegram Bot
  bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - REDIS_DB=${REDIS_DB:-0}
      - PAYMENT_ENABLED=${PAYMENT_ENABLED:-false}
      - TRIBUTE_API_KEY=${TRIBUTE_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./assets:/app/assets:ro
      - ./data:/app/data:ro

  # Redis for session storage
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
