[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -m vechnost_bot.run_webhook"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
