[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -m vechnost_bot"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
