"""add_certificates_table

Revision ID: 69fc4bb29a08
Revises: 5b5f4176ae1f
Create Date: 2025-12-05 11:23:23.612937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69fc4bb29a08'
down_revision: Union[str, None] = '5b5f4176ae1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'certificates',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('is_used', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('used_by_telegram_user_id', sa.BigInteger(), nullable=True),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index('idx_certificate_code', ['code'], unique=False)
        batch_op.create_index('idx_certificate_used_by', ['used_by_telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index('idx_certificate_used_by')
        batch_op.drop_index('idx_certificate_code')

    op.drop_table('certificates')
    # ### end Alembic commands ###
