#!/usr/bin/env python3
"""Keep the settings table in docs/ENVIRONMENT_VARIABLES.md in step with Settings.

The table of every variable `vechnost_bot.config.Settings` reads - its name,
its default and what it does - is generated from the class itself and sits
between two markers in the document; the prose around it is written by hand.
tests/test_env_docs.py fails when the committed table is not what this
script prints, so a setting cannot be added, renamed or re-described without
the document following.

    python scripts/env_docs.py           # print the table
    python scripts/env_docs.py --write   # rewrite it in the document
"""

import argparse
import os
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "docs" / "ENVIRONMENT_VARIABLES.md"
BEGIN = "<!-- settings table: generated by scripts/env_docs.py, do not edit by hand -->"
END = "<!-- end of the settings table -->"

sys.path.insert(0, str(ROOT))


def _default(field: Any) -> str:
    from pydantic_core import PydanticUndefined

    value = field.default
    if value is PydanticUndefined:
        text = "**required**"
    elif value is None:
        text = "unset"
    elif isinstance(value, bool):
        text = f"`{str(value).lower()}`"
    else:
        text = f"`{value}`"
    low = next((m.ge for m in field.metadata if hasattr(m, "ge")), None)
    high = next((m.le for m in field.metadata if hasattr(m, "le")), None)
    if low is not None and high is not None:
        text += f", {low}–{high}"
    return text


def table() -> str:
    """The Markdown table, one row per Settings field, in declaration order."""
    # Settings are built when the module is imported, and the token has no
    # default; this reads only the class, so any token will do.
    os.environ.setdefault("TELEGRAM_BOT_TOKEN", "0:settings-table")
    from vechnost_bot.config import Settings

    rows = ["| Variable | Default | What it does |", "|---|---|---|"]
    for name, field in Settings.model_fields.items():
        alias = field.validation_alias
        variable = alias if isinstance(alias, str) else name.upper()
        description = " ".join((field.description or "").split())
        # A pipe would end the cell; `<bot>` would be taken for an HTML tag.
        description = description.replace("|", "\\|").replace("<", "\\<")
        rows.append(f"| `{variable}` | {_default(field)} | {description} |")
    return "\n".join(rows) + "\n"


def rendered(document: str) -> str:
    """The document with the table between its markers replaced."""
    head, marker, rest = document.partition(BEGIN)
    _, end_marker, tail = rest.partition(END)
    if not marker or not end_marker:
        raise SystemExit(f"{DOC.relative_to(ROOT)} has lost its table markers")
    return f"{head}{BEGIN}\n{table()}{END}{tail}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--write", action="store_true",
                        help=f"rewrite the table in {DOC.relative_to(ROOT)}")
    args = parser.parse_args()
    if args.write:
        DOC.write_text(rendered(DOC.read_text(encoding="utf-8")), encoding="utf-8")
        print(f"rewrote the table in {DOC.relative_to(ROOT)}")
    else:
        print(table(), end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
